version: '3'
services:
  pihole:
    image: pihole/pihole:4.3.2
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /home/pi/docker/data/pihole/pihole/:/etc/pihole/
      - /home/pi/docker/data/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      ServerIP:
      WEBPASSWORD:
      DNS1:
      DNS2:
